extends Node

enum ENTER_SIDE { LEFT, RIGTH, TOP, BOTTOM }
enum FADE_DIRECTION { LEFT, RIGHT, UP, DOWN }

enum TERMINALS {
	COLLAPSING_STATION_01,
	ABANDONED_RAILTRACKS_01,
	ABANDONED_RAILTRACKS_02
}

enum DOORS {
	HUB_DOOR
}
