extends Node

enum ENTER_SIDE { LEFT, RIGTH, TOP, BOTTOM }
enum FADE_DIRECTION { LEFT, RIGHT, UP, DOWN }

enum TERMINALS {
	COLLAPSING_STATION_01,
	ABANDONED_RAILTRACKS_01,
	ABANDONED_RAILTRACKS_02,
	ABANDONED_RAILWAY_01,
	ABANDONED_RAILWAY_02,
	ABANDONED_RAILWAY_03,
	GARDEN_BUBKER,
	STAION_Z,
	RUINED_APARTMENTS_1,
	RUINED_APARTMENTS_2,
	RUINED_APARTMENTS_3,
	COLLAPSING_STATION_02,
	UNFINISHED_APARTMENTS_1,
}

enum DOORS {
	HUB_DOOR,
	ABANDONED_RAILWAY_LEFT,
	ABANDONED_RAILWAY_BOTTOM
}

enum ABILITIES {
	DOUBLE_JUMP,
	DASH,
	WALL_JUMP,
	UP_DASH
}
